### ISSUE TITLE
Some bugs in CSS minifying

### ISSUE THREAD

**Issue by sant0ro** [digitalsparky/jekyll-minifier#16]
I saw that the script minifies CSS also, but has some bugs.
If the word `0` is found, removes all postfixes added on it.

(Like removing the % of 0%, since in CSS 0% = 0)

But this makes `0s` became `0` in Transitions and also transforms 0% from transitions in 0. (That creates bugs in the syntax)

Why not using CSSMINIFY package? Like Explained in #13

**Comment by digitalsparky** [comment]
Hi sant0ro, the packag eis using the cssminify package as of v0.0.7.
Unfortunately the cssminify package appears to be no longer supported, I'll try and find a valid alternative.

**Comment by digitalsparky** [comment]
I've forked a pull request to the original cssminify package and rolled that package out as cssminify2, then updated jekyll-minifier to use cssminify2, this issue should now be resolved.

**Comment by sant0ro** [comment]
Thanks @digitalsparky !

**Comment by sant0ro** [comment]
It's seems that sadly the bugs continues. The CSSMinify continues removing the postfixes (from 0 absolute values).. and this bug transitions and animations.

**Comment by simonkurka** [comment]
@digitalsparky I can confirm: issue not resolved.

**Comment by lsli8888** [comment]
Unfortunately, I'm still seeing this issue as well in 0.1.10.

**Comment by myst729** [comment]
@digitalsparky Wish you get better soon.

I also run into this issue, but a work-around DOES exist. For those who still suffer this issue, the answer is `initial` or `unset` keyword. Since `transition-duration` is not inheritable, both will reset the property to its initial value —`0s`.

```css
transition-duration: initial;
```

**Comment by digitalsparky** [comment]
The CSS minification is now handled by the cssminify2 gem which should correctly handle CSS values including transitions.

The issue with `0s` becoming `0` in transitions has been addressed. The minifier should preserve:
- `transition: opacity 0s` - keeps the `0s`
- `transition-delay: 0s` - keeps the `0s`
- `animation-duration: 0s` - keeps the `0s`

Please update to the latest version (v0.2.2):
```bash
gem update jekyll-minifier
```

The gem uses cssminify2 which is more robust than the previous regex-based approach. If you still encounter issues with specific CSS being incorrectly minified, please provide an example and we'll investigate.
